export * from './get-groups.controller'
export * from './get-players.controller'
export * from './insert-players.controller'
export * from './set-clubs-random-way.controller'
export * from './set-confrontation-group-stage.controller'
export * from './set-groups.controller'
export * from './update-set-confrontation-group-stage.controller'
export * from './get-confrontation.controller'